### ISSUE TITLE
API Lending ?

### ISSUE THREAD

**Issue by trixprod** [TheCookieLab/poloniex-api-java#1]
Hello,

May we see in a near future api java code for the lending API poloniex access ?

Thx.

**Comment by TheCookieLab** [comment]
Yes I can implement that. Are you currently using the client? What's your experience been thus far?

**Comment by trixprod** [comment]
Hi !

No i just found this repo yesterday and i only need the lending api code.

I'm a Java developer too, if you need help, just ask.

**Comment by TheCookieLab** [comment]
Yeah please feel free to submit a pull request. Since I don't use the lending functionality, it would probably be better implemented by an actual user.

**Comment by hkhald01** [comment]
Hello there, I am about to start using your client api, I chose it over Xchange, because it is simpler and easier, perhaps I was wondering if you have a push client to fetch data from Poloniex ws protocol

**Comment by TheCookieLab** [comment]
Yes, I have the websocket client code as well. I'll look to add it to this project shortly.

**Comment by hkhald01** [comment]
can you please include a sample code on how to web socket,  to get data, I am using a postgres db to save all the data in, I am eager to see how is the wss performance as calling all the market ticker from your code takes about 0.6 s in avg
thanks again

**Comment by TheCookieLab** [comment]
The first-pass websocket client code (with example) can be found in branch feature/websocket-client. The trollbox subscription doesn't work correctly. Give it a try and let me know if you have any issues.

**Comment by dave0688** [comment]
Hi, 
I just started to use your API and so far it works great. 
However, as @trixprod  mentioned, I'm also really interested in the lending part of the API. Do you have a timeline in mind when you could implement it? I will also take a look at it the next days, however, not sure if I can find so much time to implement it.

But - great job so far!

**Comment by cheolhee** [comment]
Hi,
I implemented LendingService for lending APIs.

**Comment by TheCookieLab** [comment]
Thanks to contributions from dave0688 and cheolhee, the lending API is reality!
