### ISSUE TITLE
None of the api calls are working

### ISSUE THREAD

**Issue by santhosh12992** [TheCookieLab/poloniex-api-java#13]
I am using this project for more than a month and it worked fine. For the last two days, it not working as expected. However if i try the same command in my browser, it's returning the expected data. 

This is what i have tried.(simple one for debugging)

                `PoloniexPublicAPIClient bitcoin = new PoloniexPublicAPIClient();
		 System.out.println(bitcoin.returnTicker());`

This is the response from the console.
![poloniex](https://user-images.githubusercontent.com/23401123/28303916-0c533d9c-6bb3-11e7-9537-3ee4e53d8895.png)

Kindly help me to fix this.

**Comment by santhosh12992** [comment]
Update: "Please complete the security check to proceed."

**Comment by TheCookieLab** [comment]
Think this through logically:

1. Your code hasn't changed
2. You're getting a security check request

Have you checked your Poloniex account's API access settings?

**Comment by santhosh12992** [comment]
Hi, i havent made any changes in the access settings. If i hit the public return ticker in browser also, am getting the security screen first and then the json response. any thoughts?
