### ISSUE TITLE
Maven central distribution

### ISSUE THREAD

**Issue by nikita-volkov** [TheCookieLab/poloniex-api-java#15]
First of all, thanks for your work!

Why don't you distribute the project on Maven Central?

**Comment by TheCookieLab** [comment]
Thanks! I actually never thought about putting it out onto Maven. Let me look into it.

**Comment by stacksavings** [comment]
This would be great

**Comment by shikolay** [comment]
I am using this lib with jitpack.io which allow me to build jar on the fly from commits. Very handy

**Comment by TheCookieLab** [comment]
I haven't had time as of late to look into this. A pull request for the functionality would be welcome.

**Comment by TheCookieLab** [comment]
This is now available on the Maven central repo as 1.1.1-SNAPSHOT.
