### ISSUE TITLE
Problem getting result 

### ISSUE THREAD

**Issue by ArseniyChern** [TheCookieLab/poloniex-api-java#16]
Currently trying to subscribe to ticker, here is my complete code: 

```
try (WSSClient poloniexWSSClient = new WSSClient("wss://api.poloniex.com", "realm1")) {
		    poloniexWSSClient.subscribe(PoloniexSubscription.TICKER);
		    poloniexWSSClient.subscribe(new PoloniexSubscription("USDT_BTC"));
		    poloniexWSSClient.run(60000);
		} catch (ApplicationError e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
```

And yet i get this output:
```
2017-07-24 12:45:03,657 main ERROR logger Logger has no parameter that matches element Root
2017-07-24 12:45:03,664 main WARN No Root logger was configured, creating default ERROR-level Root logger with Console appender
2017-07-24 12:45:04,678 [main] TRACE WSSClient - Disconnected
2017-07-24 12:45:04,685 [WampClientEventLoop] TRACE WSSClient - Connecting...
2017-07-24 12:46:04,693 [WampClientEventLoop] TRACE WSSClient - Disconnected
```

It doesen't subscribe or anything, i dug around in your code and noticed that there is no authentication when subscribing to ticker, perhaps that's the issue? If so i would be happy to add it to contribute. I am just not as familiar with this code that you. Thanks for your help!!

**Comment by TheCookieLab** [comment]
It looks like it ran for 60 seconds as intended (looking at the existing log timestamps). Your issue is you don't have a logger defined so none of the tickers are getting displayed. Try configuring a logger and/or increase the run-time to something different to verify

**Comment by bhavishyagoyal12** [comment]
@TheCookieLab  Thanks for Reply. It should show this in logs connected but it's not doing that. I would appreciate if you could help on above since i am also getting same issue

**Comment by TheCookieLab** [comment]
This is likely just due to Poloniex not able to handle the server load / traffic. Ironically it's libraries like these that contribute to the tragedy of the commons by making it (relatively) easy to use their APIs. I would recommend opening support tickets with Poloniex as that's the only way they'll get feedback.
