### ISSUE TITLE
Issue in PoloniexWSSClientExample?

### ISSUE THREAD

**Issue by thiko** [TheCookieLab/poloniex-api-java#21]
Hi,

I'm not getting ticker data via websockets anymore. Tried with own impl. and PoloniexWSSClientExample. Do you guys have the same problem?

I cannot find any related announcement from Poloniex.

Thanks

**Comment by TheCookieLab** [comment]
How long are you allowing for the connection to take place? I've personally noticed it taking longer and longer to establish a websocket connection with Poloniex.

**Comment by thiko** [comment]
Sorry for my late reply.
The connection is established but I did not receive the tick data anymore. You can reproduce it very easy by executing the PoloniexWSSClientExample.

In my case it looks like:

> 2018-01-02 20:59:34,778 [WampClientEventLoop] TRACE WSSClient - Connecting...
> 2018-01-02 20:59:36,059 [WampClientEventLoop] TRACE WSSClient - Connected
> 2018-01-02 21:00:34,781 [WampClientEventLoop] TRACE WSSClient - Disconnected

The PoloniexSubscription isnt receiving anything :-/
Can you pls try to reproduce it? It was running for several month in a row before..

Thanks!

**Comment by TheCookieLab** [comment]
I get the same "timeout". Not quite sure why (considering the code has not changed) - first guess is Poloniex is limiting the number of active web-socket connections (can easily be checked by seeing if the "reference" Python/Node/PHP implementations suffer the same issue. 

I know Poloniex has a second "undocumented" web-socket api at wss://api2.poloniex.com but I have not had a chance to look into it.  Any digging you can do would be appreciated.

**Comment by thiko** [comment]
Yes I saw it yesterday and gave it a try today. Its possible to create a connection and receiving messages with a "plain" Websocket client (I used https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/http/websocketx/client)

My first try to receive the ticker data was the good old way ;)
> Send: {"command": "subscribe", "channel": "ticker"}
> Receive: {"error":"Invalid channel."}

I observed some channel codes instead of strings. After some time of searching around I found the ticker code: 1002. Next try:
> Send {"command": "subscribe", "channel": "1002"}
> Receive: [1002,null,[153,"0.00039881","0.00039881","0.00039423","0.06035468","53.77548143","141808.01778096",0,"0.00042049","0.00035726"]]
> .... (and so on)
(FYI: Status Codes from [Stackoverflow](https://stackoverflow.com/questions/32154121/how-to-connect-to-poloniex-com-websocket-api-using-a-python-library) )

Unfortunately, it seems to be not "wamp-able" but my personal experiences with wamp are not well-founded. It would be great when you (or someone else) find some time to verify my results. I could refactor the WSSClient class to use the Netty plain websocket-client but I would like to hear a second opinion before.

Thanks :)

**Comment by Quizious** [comment]
I'm seeing this too. Tried api2.poloniex but it doesn't go beyond the 'connecting' phase.

**Comment by TheCookieLab** [comment]
Yes, you're right - the issue does seem to associated with WAMP. If you could refactor using the "plain" websocket client, that would be greatly appreciated.

**Comment by TheCookieLab** [comment]
@thiko Can you post your Netty code? I've tried both "plain" Netty and Autobahn implementations however neither work correctly (Jawampa and Autobahn both use Netty under the covers anyway). I'm curious to see if I'm not doing something I should be. Thanks.

**Comment by thiko** [comment]
Hi @TheCookieLab ,
sure I'll commit it later today. I did not try it since ~ 1 month. Pretty stressful evenings actually >.<  Sorry...
The current test implementation is not using observables. I think it would be nice to use it again and maybe introduce these small state machine like the Wamp implementation aswell. 
I'll ping you again after commit!

**Comment by thiko** [comment]
Hey  @TheCookieLab!
I just have pushed a prototype. Please take a look https://github.com/thiko/poloniex-api-java/commit/3491bccdb01832b238b63a3156c52cdc67910a39

Its really a prototype but seems to work!
Cheers!

**Comment by TheCookieLab** [comment]
@thiko 

That's awesome! Many thanks to you for the working code. I've incorporated it into branch feature/plain-wss and will be fully integrating it shortly.

**Comment by TheCookieLab** [comment]
At long last the websocket functionality works again, and uses Poloniex's (currently undocumented) wss://api2.poloniex.com endpoint. 

@thiko many thanks for your help on this, I greatly appreciate it.
