### ISSUE TITLE
Feedback on ExchangeService Interface - Thoughts on implementing for other Exchanges?

### ISSUE THREAD

**Issue by TheCookieLab** [TheCookieLab/poloniex-api-java#27]
I'm curious what, if any, improvements we can make to the existing ExchangeService interface. Given a solid interface, I'd be interested in implementing the functionality for other exchanges like GDAX and Bittrex. Thoughts?

**Comment by thiko** [comment]
After taking brief look on the [Bittrex API](https://bittrex.com/home/api) it seems to match the actual ExchangeService and is easy to use (not sure about the loan part). Furthermore, they also provide a non-documented websocket implementation ([here](https://github.com/dparlevliet/node.bittrex.api/tree/master/examples) a JS client impl).

I cannot find any real challenge (for Bittrex) but it would be a clear added value.
:+1:
