### ISSUE TITLE
ERROR PoloniexExchangeService - Error retrieving all markets - java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

### ISSUE THREAD

**Issue by RostyslavBortman** [TheCookieLab/poloniex-api-java#28]
Here is a code which I using:
`String apiKey = "REMOVED";
String apiSecret = "REMOVED";
PoloniexExchangeService service = new PoloniexExchangeService(apiKey, apiSecret);
List<String> marketsList = service.returnAllMarkets();`
What is wrong with it? The message of exception is: **ERROR PoloniexExchangeService - Error retrieving all markets - java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $**

**Comment by Quizious** [comment]
Dude... that appears to be your true api-keys with which someone could just transfer all your coins. (Or copy them and try to use them later, if you don't have any coins on the exchange at the moment).
Remove the keys and make new ones.

**Comment by RostyslavBortman** [comment]
Don't worry, It was creating just for testing 👍 
But the problem is still exist. How I can fix it?

**Comment by RostyslavBortman** [comment]
Any method which I call from **PoloniexExchangeService service**, throw the error, like I wrote above

**Comment by TheCookieLab** [comment]
If you debug and step through, you'll see the actual (likely HTML) error returned by Poloniex. The exception you're seeing is due to Gson unable to parse the non-json response.

**Comment by vaa25** [comment]
@TheCookieLab 
>you'll see the actual (likely HTML) error returned by Poloniex

Why Poloniex returns error for request that don't requires authentication?

**Comment by TheCookieLab** [comment]
There are many possible scenarios. 404 Not Found is one.

**Comment by TheCookieLab** [comment]
While there's an opportunity for more human readable error messages when this occurs, this event itself is not a defect.

**Comment by vaa25** [comment]
@TheCookieLab no, simple request from browser https://poloniex.com/public?command=returnTicker works fine, but this code fails:
```
new PoloniexExchangeService(apiKey, apiSecret).returnTicker()
```

**Comment by TheCookieLab** [comment]
I just called it successfully. Either you are blacklisted or you don't have your API access configured correctly.

**Comment by vaa25** [comment]
Above request is public. It no need any configuration. It should be simple GET request. And it work for me in browser, but not in this api.

**Comment by TheCookieLab** [comment]
Like I said, your (or your country's) IP range is probably blacklisted from programmatic access form any non-browser user agent.
