### ISSUE TITLE
Poloniex reCAPTCHA issue

### ISSUE THREAD

**Issue by JPLeoRX** [TheCookieLab/poloniex-api-java#29]
This API seems to be no longer working due to weird Poloniex security measures. When making a request using this Java API or even using directly Poloniex REST endpoints I keep receiving their reCAPTCHA page as a response. 

Seems like Poloniex doesn't want us to use their REST api anymore 👍

**Comment by TheCookieLab** [comment]
What country are you located in? I am still able to call the REST API (USA). When I was visiting China last summer, none of the APIs worked and I assume I was IP range blocked.

**Comment by JPLeoRX** [comment]
I'm currently in Ukraine, but I was also having the same issue while I was staying in Turkey. So Poloniex is just blocking all the 3rd-world countries 😄 

Thanks, now I at least understand why I'm having this weird problem. And I'm also relieved to know that it's still working in the US.

**Comment by TheCookieLab** [comment]
I’d be curious if you can make a small change (probably a setting on the HTTPClient) to present a different user agent (like a browser) to “fool” Poloniex.

**Comment by achavan51** [comment]
You can follow this blog:
sandeeppatidar458898926.wordpress.com

**Comment by TheCookieLab** [comment]
I don't really want to add proxy functionality to the base project, especially not "hard-coding" use of ProxyNova. Adding configuration flexibility for arbitrary proxy providers is not in scope of this project.
