### ISSUE TITLE
buy and sell ? how to 

### ISSUE THREAD

**Issue by albertls** [TheCookieLab/poloniex-api-java#3]
how to get a responde from a buy and sell methods?

PoloniexExchangeService polo = new PoloniexExchangeService(apiKey, apiSecret);
          BigDecimal valor = new BigDecimal("0.00020018");
          BigDecimal quantidade = new BigDecimal("0.00000001");
   polo.buy("BTC_XRP", valor, quantidade,false,false,false));

  i am trying to place an order but without sucess... 

can you give a example for those operations?

**Comment by TheCookieLab** [comment]
So did you debug the output from your buy execution?

**Comment by albertls** [comment]
how i can do this? any example?

**Comment by albertls** [comment]
Sorry... i find the error!
