### ISSUE TITLE
Open orders seems not working

### ISSUE THREAD

**Issue by Barrett17** [TheCookieLab/poloniex-api-java#5]
I tried today to test open orders, and I get the following exception from gson:

ERROR com.cf.client.poloniex.PoloniexExchangeService - Error retrieving open orders for BTC_LTC - java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 3 path $[0]

However I had to do the following modify to get it compile with jre 1.7, not sure if it's related.

```
-        return openOrders.getOrDefault(currencyPair, new ArrayList<>());
+        return openOrders.getOrDefault(currencyPair, new ArrayList<PoloniexOpenOrder>());
```

**Comment by TheCookieLab** [comment]
First, you should pull the latest. There was a fix to the open order call. 

Second, this is a Java 8 project. If you need it to work with 7, you'll need to fork it.

**Comment by Barrett17** [comment]
I downloaded eclipse neon and set everything to Java 8, refreshed maven dependencies and rebuilt the library using a package goal but the issue is still there.

**Comment by Barrett17** [comment]
So, slight update, it seems some currencies work OK, others give me this error.

**Comment by TheCookieLab** [comment]
Did you re-clone/re-download this library? It was updated 5 days ago. If some currency pairs work and others don't, you're probably passing in invalid values. Place a break point after the API call to Poloniex and before the mapping step to see what Poloniex returned.
