### ISSUE TITLE
returnOpenOrders

### ISSUE THREAD

**Issue by koss89** [TheCookieLab/poloniex-api-java#6]
Good day, found an error in this function, more precisely the query is implemented only for a specific trading pair, but the mapping results from a general sample, and there is no mapping for a particular pair, I did not find the general sample function at all in Api, well,
`Map <String, List <PoloniexOpenOrder >> openOrders = gson.fromJson (openOrdersResults, new TypeToken <Map <String, List <PoloniexOpenOrder >>> ()   {         } .getType ());`

Should be:
```
List <PoloniexOpenOrder > openOrders = gson.fromJson (openOrdersResults, 
new TypeToken List <PoloniexOpenOrder >> ()     {         } .getType ());
```

Well, to implement a selection of open orders for all pairs, the mapping already exists :)

**Comment by TheCookieLab** [comment]
Thanks, should be fixed in the master branch now.
